-- Production migration. Do not replace with GORM AutoMigrate.

CREATE TABLE finance_users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('user', 'admin')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE finance_claim_drafts (
  id TEXT PRIMARY KEY,
  owner_id INTEGER NOT NULL REFERENCES finance_users(id),
  text TEXT NOT NULL,
  horizon TEXT,
  items JSONB NOT NULL DEFAULT '[]',
  revision INTEGER NOT NULL DEFAULT 1,
  as_of TIMESTAMPTZ NOT NULL,
  mode TEXT NOT NULL CHECK (mode IN ('fixture', 'live')),
  parse_usage_id TEXT,
  confirmed_run_id TEXT,
  config_versions JSONB NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX finance_claim_drafts_owner_created ON finance_claim_drafts (owner_id, created_at DESC);

CREATE TABLE finance_research_runs (
  id TEXT PRIMARY KEY,
  owner_id INTEGER NOT NULL REFERENCES finance_users(id),
  draft_id TEXT NOT NULL REFERENCES finance_claim_drafts(id),
  parent_run_id TEXT,
  claim_snapshot JSONB NOT NULL,
  instrument_id TEXT NOT NULL,
  horizon TEXT NOT NULL,
  as_of TIMESTAMPTZ NOT NULL,
  mode TEXT NOT NULL CHECK (mode IN ('fixture', 'live')),
  status TEXT NOT NULL CHECK (status IN ('queued','researching','verifying','completed','incomplete','failed','canceling','canceled')),
  stage TEXT NOT NULL,
  config_versions JSONB NOT NULL,
  budget_snapshot JSONB NOT NULL,
  idempotency_key TEXT NOT NULL,
  request_hash TEXT NOT NULL,
  started_at TIMESTAMPTZ,
  deadline_at TIMESTAMPTZ,
  lease_owner TEXT,
  lease_until TIMESTAMPTZ,
  version BIGINT NOT NULL DEFAULT 1,
  deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (owner_id, idempotency_key)
);
CREATE INDEX finance_research_runs_owner_history ON finance_research_runs (owner_id, created_at DESC, id DESC);
CREATE INDEX finance_research_runs_status_lease ON finance_research_runs (status, lease_until);
CREATE UNIQUE INDEX finance_research_runs_one_active
  ON finance_research_runs (owner_id)
  WHERE status IN ('queued','researching','verifying','canceling');

CREATE TABLE finance_research_tasks (
  id TEXT PRIMARY KEY,
  run_id TEXT NOT NULL REFERENCES finance_research_runs(id),
  role TEXT NOT NULL CHECK (role IN ('supporter','challenger')),
  status TEXT NOT NULL,
  payload_hash TEXT NOT NULL,
  attempt INTEGER NOT NULL DEFAULT 1,
  worker_task_id TEXT,
  result JSONB,
  heartbeat_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (run_id, role),
  UNIQUE (worker_task_id)
);

CREATE TABLE finance_evidence (
  id TEXT PRIMARY KEY,
  run_id TEXT NOT NULL REFERENCES finance_research_runs(id),
  instrument_id TEXT NOT NULL,
  source_id TEXT NOT NULL,
  source_url TEXT NOT NULL,
  source_kind TEXT NOT NULL CHECK (source_kind IN ('filing','financials','market','news','fixture')),
  title TEXT NOT NULL,
  locator TEXT NOT NULL,
  text TEXT NOT NULL,
  metrics JSONB NOT NULL DEFAULT '[]',
  published_at TIMESTAMPTZ NOT NULL,
  available_at TIMESTAMPTZ NOT NULL,
  retrieved_at TIMESTAMPTZ NOT NULL,
  content_hash TEXT NOT NULL,
  data_version TEXT NOT NULL,
  mode TEXT NOT NULL CHECK (mode IN ('fixture', 'live')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (run_id, source_id, content_hash, locator)
);

CREATE TABLE finance_task_evidence (
  task_id TEXT NOT NULL REFERENCES finance_research_tasks(id),
  evidence_id TEXT NOT NULL REFERENCES finance_evidence(id),
  PRIMARY KEY (task_id, evidence_id)
);

CREATE TABLE finance_calculations (
  id TEXT PRIMARY KEY,
  run_id TEXT NOT NULL REFERENCES finance_research_runs(id),
  task_id TEXT NOT NULL REFERENCES finance_research_tasks(id),
  grant_id TEXT NOT NULL,
  operation TEXT NOT NULL,
  inputs JSONB NOT NULL,
  formula TEXT NOT NULL,
  precision INTEGER NOT NULL,
  result NUMERIC NOT NULL,
  unit TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (grant_id)
);

CREATE TABLE finance_reports (
  id TEXT PRIMARY KEY,
  run_id TEXT NOT NULL REFERENCES finance_research_runs(id),
  version INTEGER NOT NULL,
  quality_status TEXT NOT NULL,
  body JSONB NOT NULL,
  validator_version TEXT NOT NULL,
  verification JSONB NOT NULL,
  published_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (run_id, version)
);

CREATE TABLE finance_questions (
  id TEXT PRIMARY KEY,
  run_id TEXT NOT NULL REFERENCES finance_research_runs(id),
  owner_id INTEGER NOT NULL REFERENCES finance_users(id),
  idempotency_key TEXT NOT NULL,
  request_hash TEXT NOT NULL,
  body TEXT NOT NULL,
  response JSONB,
  status TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (owner_id, run_id, idempotency_key)
);

CREATE TABLE finance_config_versions (
  id TEXT PRIMARY KEY,
  kind TEXT NOT NULL,
  config_digest TEXT NOT NULL,
  public_config JSONB NOT NULL,
  secret_ciphertext BYTEA,
  secret_key_version TEXT,
  test_status TEXT NOT NULL,
  test_digest TEXT,
  active_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE finance_usage_ledger (
  id TEXT PRIMARY KEY,
  owner_id INTEGER NOT NULL REFERENCES finance_users(id),
  run_id TEXT,
  task_id TEXT,
  question_id TEXT,
  parse_id TEXT,
  request_id TEXT NOT NULL UNIQUE,
  purpose TEXT NOT NULL,
  kind TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('reserved','succeeded','failed','unknown')),
  reserved_tokens INTEGER NOT NULL,
  actual_tokens INTEGER,
  upstream_request_id TEXT,
  error_code TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE finance_tool_grants (
  id TEXT PRIMARY KEY,
  request_id TEXT NOT NULL UNIQUE,
  run_id TEXT NOT NULL REFERENCES finance_research_runs(id),
  task_id TEXT NOT NULL REFERENCES finance_research_tasks(id),
  tool_name TEXT NOT NULL,
  args_hash TEXT NOT NULL,
  status TEXT NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  output_hash TEXT,
  executed BOOLEAN NOT NULL DEFAULT FALSE,
  params_hash TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE finance_data_records (
  id TEXT PRIMARY KEY,
  grant_id TEXT NOT NULL REFERENCES finance_tool_grants(id),
  record_hash TEXT NOT NULL,
  payload JSONB NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (grant_id, record_hash)
);

CREATE TABLE finance_model_cache (
  run_id TEXT NOT NULL,
  task_id TEXT NOT NULL,
  request_id TEXT NOT NULL,
  owner_id INTEGER NOT NULL REFERENCES finance_users(id),
  purpose TEXT NOT NULL DEFAULT 'research',
  body_hash TEXT NOT NULL,
  status TEXT NOT NULL,
  response JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (run_id, task_id, request_id)
);

CREATE TABLE finance_internal_tokens (
  token_hash TEXT PRIMARY KEY,
  run_id TEXT NOT NULL,
  task_id TEXT NOT NULL,
  purpose TEXT NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  revoked_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE finance_scheduler (
  singleton_id TEXT PRIMARY KEY,
  policy_version TEXT NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
INSERT INTO finance_scheduler (singleton_id, policy_version) VALUES ('global', 'policy_v1')
ON CONFLICT (singleton_id) DO NOTHING;

ALTER TABLE finance_research_runs
  ADD CONSTRAINT finance_research_runs_parent_fk
  FOREIGN KEY (parent_run_id) REFERENCES finance_research_runs(id);
