package strategy

import (
	"bytes"
	"encoding/json"
	"fmt"
	"sort"
	"strconv"
	"strings"

	"github.com/shopspring/decimal"

	"zhigu/server/service/finance"
	"zhigu/server/service/indicators"
)

const (
	EditorSchemaVersion = "strategy.editor.v1"
	MarketSchemaVersion = "strategy.market.v1"
	MaxRepeat           = 20
	MaxWindowDays       = 20
)

// EditorState is the visual rule-editor state (strategy.editor.v1). Interface
// node ids / expand state live in ui_metadata and never enter the semantic hash.
type EditorState struct {
	Name         string            `json:"name"`
	InstrumentID *string           `json:"instrument_id"`
	SignalPeriod string            `json:"signal_period"`
	PriceBasis   string            `json:"price_basis"`
	Indicators   []indicators.Spec `json:"indicators"`
	Entry        json.RawMessage   `json:"entry"`
	Exit         json.RawMessage   `json:"exit"`
	Position     Position          `json:"position"`
	Risk         Risk              `json:"risk"`
	Execution    Execution         `json:"execution"`
	UIMetadata   json.RawMessage   `json:"ui_metadata,omitempty"`
}

// ContinuityCheck is generated by the server compiler and stored inside the
// trusted compiled artifact (it participates in the compiled hash). The browser
// cannot supply or strip these checks; evaluation must run them. Path binds the
// check to its condition node (e.g. "entry", "entry/all[1]"), so an entry window
// never gates exit or another OR branch.
type ContinuityCheck struct {
	Kind    string `json:"kind"` // consecutive_rising_volume
	Ref     string `json:"ref"`  // volume
	Days    int    `json:"days"`
	BaseLag int    `json:"base_lag"`
	Path    string `json:"path"`
}

// InstrumentBinding belongs to the strategy.market.v1 rule template envelope.
type InstrumentBinding struct {
	Mode    string   `json:"mode"` // select_one
	Markets []string `json:"markets"`
}

// MarketTemplate is the immutable rule_template stored on market versions.
type MarketTemplate struct {
	SchemaVersion     string            `json:"schema_version"`
	EditorState       EditorState       `json:"editor_state"`
	InstrumentBinding InstrumentBinding `json:"instrument_binding"`
}

type EditorResult struct {
	Status     string            `json:"status"` // ready | needs_clarification
	Missing    []string          `json:"missing_fields"`
	Document   *Document         `json:"document,omitempty"`
	Compiled   *Compiled         `json:"compiled,omitempty"`
	Continuity []ContinuityCheck `json:"continuity_checks"`
}

func ParseEditorState(raw []byte) (EditorState, error) {
	dec := json.NewDecoder(bytes.NewReader(raw))
	dec.DisallowUnknownFields()
	var st EditorState
	if err := dec.Decode(&st); err != nil {
		return EditorState{}, finance.NewError(422, "validation", "STRATEGY_INVALID", "编辑状态 JSON 无法解析或含未知字段")
	}
	return st, nil
}

func ParseMarketTemplate(raw []byte) (MarketTemplate, error) {
	dec := json.NewDecoder(bytes.NewReader(raw))
	dec.DisallowUnknownFields()
	var tpl MarketTemplate
	if err := dec.Decode(&tpl); err != nil {
		return MarketTemplate{}, finance.NewError(422, "validation", "STRATEGY_INVALID", "规则模板 JSON 无法解析或含未知字段")
	}
	if tpl.SchemaVersion != MarketSchemaVersion {
		return MarketTemplate{}, finance.NewError(422, "validation", "STRATEGY_INVALID", "规则模板 schema_version 必须为 "+MarketSchemaVersion)
	}
	if tpl.InstrumentBinding.Mode != "select_one" {
		return MarketTemplate{}, finance.NewError(422, "validation", "STRATEGY_INVALID", "instrument_binding.mode 仅支持 select_one")
	}
	if len(tpl.InstrumentBinding.Markets) == 0 {
		return MarketTemplate{}, finance.NewError(422, "validation", "STRATEGY_INVALID", "instrument_binding.markets 不能为空")
	}
	for _, m := range tpl.InstrumentBinding.Markets {
		if m != "A" && m != "HK" {
			return MarketTemplate{}, finance.NewError(422, "validation", "STRATEGY_INVALID", "instrument_binding.markets 仅支持 A 或 HK")
		}
	}
	return tpl, nil
}

// CompileEditor expands and compiles editor state into strategy.v2 + compiled.
// Illegal complete input returns an error; merely incomplete input returns
// status needs_clarification with field-level missing_fields and no executable
// DSL/compiled (§12.4.4).
func CompileEditor(state EditorState, instrumentOverride string) (EditorResult, error) {
	if missing := missingEditorFields(state, instrumentOverride); len(missing) > 0 {
		sort.Strings(missing)
		return EditorResult{Status: "needs_clarification", Missing: missing, Continuity: []ContinuityCheck{}}, nil
	}

	ec := &expandCtx{}
	entry, err := expandCond(state.Entry, ec, "entry", "entry")
	if err != nil {
		return EditorResult{}, err
	}
	exit, err := expandCond(state.Exit, ec, "exit", "exit")
	if err != nil {
		return EditorResult{}, err
	}

	inst := instrumentOverride
	if strings.TrimSpace(inst) == "" && state.InstrumentID != nil {
		inst = *state.InstrumentID
	}
	doc := Document{
		SchemaVersion: SchemaVersionV2,
		Name:          state.Name,
		InstrumentID:  inst,
		SignalPeriod:  state.SignalPeriod,
		PriceBasis:    state.PriceBasis,
		Indicators:    state.Indicators,
		Entry:         entry,
		Exit:          exit,
		Position:      state.Position,
		Risk:          state.Risk,
		Execution:     state.Execution,
	}
	compiled, err := Compile(doc)
	if err != nil {
		return EditorResult{}, err
	}
	compiled.Continuity = ec.checks
	docCopy := compiled.Normalized
	return EditorResult{
		Status: "ready", Missing: []string{},
		Document: &docCopy, Compiled: &compiled, Continuity: ec.checks,
	}, nil
}

func missingEditorFields(state EditorState, instrumentOverride string) []string {
	var missing []string
	if strings.TrimSpace(state.Name) == "" {
		missing = append(missing, "name")
	}
	if strings.TrimSpace(instrumentOverride) == "" && (state.InstrumentID == nil || strings.TrimSpace(*state.InstrumentID) == "") {
		missing = append(missing, "instrument_id")
	}
	if strings.TrimSpace(state.SignalPeriod) == "" {
		missing = append(missing, "signal_period")
	}
	if len(bytes.TrimSpace(state.Entry)) == 0 {
		missing = append(missing, "entry")
	}
	if len(bytes.TrimSpace(state.Exit)) == 0 {
		missing = append(missing, "exit")
	}
	if strings.TrimSpace(state.Position.Value) == "" {
		missing = append(missing, "position.value")
	}
	if m := missingCondFields(state.Entry, "entry"); m != "" {
		missing = append(missing, m)
	}
	if m := missingCondFields(state.Exit, "exit"); m != "" {
		missing = append(missing, m)
	}
	return missing
}

// missingCondFields reports the first placeholder operand (null / absent) in a
// condition tree; present-but-wrong values are hard errors, not missing fields.
func missingCondFields(raw json.RawMessage, section string) string {
	var obj map[string]json.RawMessage
	if json.Unmarshal(raw, &obj) != nil || obj == nil {
		return ""
	}
	for _, key := range []string{"all", "any"} {
		if list, ok := obj[key]; ok {
			var items []json.RawMessage
			_ = json.Unmarshal(list, &items)
			for _, it := range items {
				if m := missingCondFields(it, section); m != "" {
					return m
				}
			}
			return ""
		}
	}
	if not, ok := obj["not"]; ok {
		return missingCondFields(not, section)
	}
	if kind, ok := obj["kind"]; ok {
		_ = kind
		if len(bytes.TrimSpace(obj["days"])) == 0 {
			return section
		}
		return ""
	}
	if len(bytes.TrimSpace(obj["op"])) == 0 {
		return section
	}
	if len(bytes.TrimSpace(obj["left"])) == 0 || bytes.Equal(bytes.TrimSpace(obj["left"]), []byte("null")) {
		return section
	}
	if len(bytes.TrimSpace(obj["right"])) == 0 || bytes.Equal(bytes.TrimSpace(obj["right"]), []byte("null")) {
		return section
	}
	return ""
}

type expandCtx struct {
	checks []ContinuityCheck
}

// expandCond turns one editor condition tree into strategy.v2 nodes: repeat
// leaves fan out to `all` copies whose operand lags carry copy offset + own lag,
// and volume_increase expands to day-over-day comparisons plus a trusted
// continuity check bound to that node's path (§12.4.3, 策略附录 §5.2).
func expandCond(raw json.RawMessage, ec *expandCtx, section, path string) (json.RawMessage, error) {
	if len(bytes.TrimSpace(raw)) == 0 || bytes.Equal(bytes.TrimSpace(raw), []byte("null")) {
		return nil, finance.NewError(422, "validation", "STRATEGY_INVALID", section+" 缺少条件")
	}
	var obj map[string]json.RawMessage
	if err := json.Unmarshal(raw, &obj); err != nil || obj == nil {
		return nil, finance.NewError(422, "validation", "STRATEGY_INVALID", section+" 条件不是对象")
	}
	if _, ok := obj["all"]; ok {
		if len(obj) != 1 {
			return nil, finance.NewError(422, "validation", "STRATEGY_INVALID", section+" 条件组只允许 all/any/not 之一")
		}
		return expandGroup(obj, "all", ec, section, path)
	}
	if _, ok := obj["any"]; ok {
		if len(obj) != 1 {
			return nil, finance.NewError(422, "validation", "STRATEGY_INVALID", section+" 条件组只允许 all/any/not 之一")
		}
		return expandGroup(obj, "any", ec, section, path)
	}
	if not, ok := obj["not"]; ok {
		if len(obj) != 1 {
			return nil, finance.NewError(422, "validation", "STRATEGY_INVALID", section+" 条件组只允许 all/any/not 之一")
		}
		expanded, err := expandCond(not, ec, section, joinPath(path, "not"))
		if err != nil {
			return nil, err
		}
		return marshalRaw(map[string]any{"not": json.RawMessage(expanded)})
	}
	if kindRaw, ok := obj["kind"]; ok {
		return expandShortcut(obj, kindRaw, ec, section, path)
	}
	if _, ok := obj["op"]; ok {
		return expandLeaf(obj, ec, section)
	}
	return nil, finance.NewError(422, "validation", "STRATEGY_INVALID", section+" 条件节点无法识别")
}

// joinPath builds the expanded-tree path segments used identically by the
// compiler (check binding) and the evaluator (check lookup).
func joinPath(path, seg string) string {
	if path == "" {
		return seg
	}
	return path + "/" + seg
}

// relCheckPath strips the "entry"/"exit" root segment so a check can be matched
// against nodes of its own subtree.
func relCheckPath(p string) string {
	if p == "" {
		return ""
	}
	if i := strings.IndexByte(p, '/'); i >= 0 {
		return p[i+1:]
	}
	return ""
}

// ChecksUnder returns checks bound to nodes inside the given root ("entry" or
// "exit"). Callers evaluating one subtree must pass only that subtree's checks.
func ChecksUnder(checks []ContinuityCheck, root string) []ContinuityCheck {
	out := make([]ContinuityCheck, 0, len(checks))
	for _, c := range checks {
		if c.Path == "" || c.Path == root || strings.HasPrefix(c.Path, root+"/") {
			out = append(out, c)
		}
	}
	return out
}

func expandGroup(obj map[string]json.RawMessage, key string, ec *expandCtx, section, path string) (json.RawMessage, error) {
	list := obj[key]
	var items []json.RawMessage
	if err := json.Unmarshal(list, &items); err != nil || len(items) == 0 {
		return nil, finance.NewError(422, "validation", "STRATEGY_INVALID", section+" 的 "+key+" 必须是非空数组")
	}
	out := make([]json.RawMessage, 0, len(items))
	for i, it := range items {
		expanded, err := expandCond(it, ec, section, joinPath(path, key+"["+itoaIndex(i)+"]"))
		if err != nil {
			return nil, err
		}
		out = append(out, expanded)
	}
	return marshalRaw(map[string]any{key: out})
}

func itoaIndex(i int) string {
	return strconv.Itoa(i)
}

func expandLeaf(obj map[string]json.RawMessage, ec *expandCtx, section string) (json.RawMessage, error) {
	for k := range obj {
		switch k {
		case "op", "left", "right", "lag", "repeat":
		default:
			return nil, finance.NewError(422, "validation", "STRATEGY_INVALID", section+" 叶节点含未知字段 "+k)
		}
	}
	op := strings.Trim(string(obj["op"]), `"`)
	switch op {
	case "gt", "gte", "lt", "lte", "eq", "crosses_above", "crosses_below":
	default:
		return nil, finance.NewError(422, "validation", "STRATEGY_INVALID", section+" 不支持的比较运算")
	}
	nodeLag, err := intField(obj, "lag", 0, 0, MaxLag)
	if err != nil {
		return nil, err
	}
	repeat, err := intField(obj, "repeat", 1, 1, MaxRepeat)
	if err != nil {
		return nil, err
	}
	left, err := parseOperandV2(obj["left"])
	if err != nil {
		return nil, err
	}
	right, err := parseOperandV2(obj["right"])
	if err != nil {
		return nil, err
	}
	copies := make([]json.RawMessage, 0, repeat)
	for k := 0; k < repeat; k++ {
		l, err := left.shift(nodeLag + k)
		if err != nil {
			return nil, err
		}
		r, err := right.shift(nodeLag + k)
		if err != nil {
			return nil, err
		}
		raw, err := marshalRaw(map[string]any{"op": op, "left": l.marshal(), "right": r.marshal()})
		if err != nil {
			return nil, err
		}
		copies = append(copies, raw)
	}
	return combineCopies(copies)
}

func expandShortcut(obj map[string]json.RawMessage, kindRaw json.RawMessage, ec *expandCtx, section, path string) (json.RawMessage, error) {
	kind := strings.Trim(string(kindRaw), `"`)
	if kind != "volume_increase" {
		return nil, finance.NewError(422, "validation", "STRATEGY_UNSUPPORTED", section+" 不支持的快捷条件 "+kind)
	}
	for k := range obj {
		switch k {
		case "kind", "days", "repeat":
		default:
			return nil, finance.NewError(422, "validation", "STRATEGY_INVALID", section+" 快捷节点含未知字段 "+k)
		}
	}
	days, err := intField(obj, "days", 0, 1, MaxWindowDays)
	if err != nil {
		return nil, err
	}
	repeat, err := intField(obj, "repeat", 1, 1, MaxRepeat)
	if err != nil {
		return nil, err
	}
	copies := make([]json.RawMessage, 0, repeat)
	for k := 0; k < repeat; k++ {
		base := k
		pairs := make([]json.RawMessage, 0, days)
		for j := 0; j < days; j++ {
			left := operandV2{Kind: "ref", Ref: "volume", Lag: base + j}
			right := operandV2{Kind: "ref", Ref: "volume", Lag: base + j + 1}
			raw, err := marshalRaw(map[string]any{"op": "gt", "left": left.marshal(), "right": right.marshal()})
			if err != nil {
				return nil, err
			}
			pairs = append(pairs, raw)
		}
		ec.checks = append(ec.checks, ContinuityCheck{Kind: "consecutive_rising_volume", Ref: "volume", Days: days, BaseLag: base, Path: path})
		copyCond, err := marshalRaw(map[string]any{"all": pairs})
		if err != nil {
			return nil, err
		}
		copies = append(copies, copyCond)
	}
	sort.SliceStable(ec.checks, func(i, j int) bool {
		a, b := ec.checks[i], ec.checks[j]
		if a.Days != b.Days {
			return a.Days < b.Days
		}
		return a.BaseLag < b.BaseLag
	})
	return combineCopies(copies)
}

func combineCopies(copies []json.RawMessage) (json.RawMessage, error) {
	if len(copies) == 1 {
		return copies[0], nil
	}
	return marshalRaw(map[string]any{"all": copies})
}

type operandV2 struct {
	Kind     string // constant | ref
	Constant string
	Ref      string
	Lag      int
}

func parseOperandV2(raw json.RawMessage) (operandV2, error) {
	if len(bytes.TrimSpace(raw)) == 0 || bytes.Equal(bytes.TrimSpace(raw), []byte("null")) {
		return operandV2{}, finance.NewError(422, "validation", "STRATEGY_INVALID", "操作数缺失")
	}
	var obj map[string]any
	if json.Unmarshal(raw, &obj) == nil && obj != nil {
		if c, ok := obj["constant"]; ok {
			s, _ := c.(string)
			if _, err := decimal.NewFromString(s); err != nil {
				return operandV2{}, finance.NewError(422, "validation", "STRATEGY_INVALID", "常数必须是十进制字符串")
			}
			if len(obj) != 1 {
				return operandV2{}, finance.NewError(422, "validation", "STRATEGY_INVALID", "常数操作数只允许 constant 字段")
			}
			return operandV2{Kind: "constant", Constant: s}, nil
		}
		ref, ok := obj["ref"].(string)
		if !ok || ref == "" {
			return operandV2{}, finance.NewError(422, "validation", "STRATEGY_INVALID", "ref 操作数缺少引用")
		}
		for k := range obj {
			if k != "ref" && k != "lag" {
				return operandV2{}, finance.NewError(422, "validation", "STRATEGY_INVALID", "ref 操作数只允许 ref 与 lag 字段")
			}
		}
		lag := 0
		if lr, ok := obj["lag"]; ok {
			switch v := lr.(type) {
			case float64:
				lag = int(v)
			case int:
				lag = v
			default:
				return operandV2{}, finance.NewError(422, "validation", "STRATEGY_INVALID", "lag 必须是整数")
			}
			if lag < 0 || lag > MaxLag {
				return operandV2{}, finance.NewError(422, "validation", "STRATEGY_INVALID", "lag 仅允许 0～250")
			}
		}
		return operandV2{Kind: "ref", Ref: ref, Lag: lag}, nil
	}
	var ref string
	if err := json.Unmarshal(raw, &ref); err != nil || ref == "" {
		return operandV2{}, finance.NewError(422, "validation", "STRATEGY_INVALID", "操作数无法解析")
	}
	return operandV2{Kind: "ref", Ref: ref}, nil
}

func (o operandV2) shift(n int) (operandV2, error) {
	if o.Kind != "ref" {
		return o, nil
	}
	o.Lag += n
	if o.Lag > MaxLag {
		return operandV2{}, finance.NewError(422, "validation", "STRATEGY_INVALID", "展开后 lag 超过 250，请精简持续天数或滞后")
	}
	return o, nil
}

// marshal normalizes operands deterministically: constant stays an object,
// lag-0 refs collapse to the bare string form, lagged refs use {ref,lag}.
func (o operandV2) marshal() any {
	if o.Kind == "constant" {
		return map[string]any{"constant": o.Constant}
	}
	if o.Lag == 0 {
		return o.Ref
	}
	return map[string]any{"ref": o.Ref, "lag": o.Lag}
}

func intField(obj map[string]json.RawMessage, key string, def, min, max int) (int, error) {
	raw, ok := obj[key]
	if !ok {
		return def, nil
	}
	var v int
	if err := json.Unmarshal(raw, &v); err != nil {
		return 0, finance.NewError(422, "validation", "STRATEGY_INVALID", key+" 必须是整数")
	}
	if v < min || v > max {
		return 0, finance.NewError(422, "validation", "STRATEGY_INVALID", fmt.Sprintf("%s 仅允许 %d～%d", key, min, max))
	}
	return v, nil
}

func marshalRaw(v any) (json.RawMessage, error) {
	b, err := json.Marshal(v)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(b), nil
}

// maxCondLag returns the largest node/operand lag in a condition tree (v2 warmup
// must cover it: 组合条件取最大预热，再覆盖最大 lag 和交叉判定所需的前一根).
func maxCondLag(raw json.RawMessage) int {
	var obj map[string]json.RawMessage
	if json.Unmarshal(raw, &obj) != nil || obj == nil {
		return 0
	}
	m := 0
	for _, key := range []string{"all", "any"} {
		if list, ok := obj[key]; ok {
			var items []json.RawMessage
			_ = json.Unmarshal(list, &items)
			for _, it := range items {
				if l := maxCondLag(it); l > m {
					m = l
				}
			}
		}
	}
	if not, ok := obj["not"]; ok {
		if l := maxCondLag(not); l > m {
			m = l
		}
	}
	if lagRaw, ok := obj["lag"]; ok {
		var l int
		if json.Unmarshal(lagRaw, &l) == nil && l > m {
			m = l
		}
	}
	for _, key := range []string{"left", "right"} {
		if opRaw, ok := obj[key]; ok {
			var o map[string]any
			if json.Unmarshal(opRaw, &o) == nil && o != nil {
				switch v := o["lag"].(type) {
				case float64:
					if int(v) > m {
						m = int(v)
					}
				case int:
					if v > m {
						m = v
					}
				}
			}
		}
	}
	return m
}

// EvalCondWithChecks evaluates a condition tree under the trusted continuity
// checks compiled with it (§12.4.3: 求值必须执行这些检查). Checks are bound to
// nodes by Path; when evaluating one subtree (entry or exit) pass only that
// subtree's checks via ChecksUnder.
func EvalCondWithChecks(raw json.RawMessage, checks []ContinuityCheck, bars []indicators.Bar, series []indicators.Series, i int) (bool, bool) {
	e := newEnv(bars, series)
	e.checks = checks
	return e.condAt(raw, i, "", true)
}

// checkContinuity enforces the consecutive-window rules computable from the bar
// sequence: an incomplete window is data-insufficient, and a known zero-volume
// day inside the window breaks continuity. Callers must pass the complete
// trading-day sequence, so consecutive entries are adjacent trading days;
// calendar gaps are rejected upstream at data preparation.
func checkContinuity(c ContinuityCheck, bars []indicators.Bar, i int) (bool, bool) {
	hi := i - c.BaseLag
	lo := hi - c.Days
	if lo < 0 || hi < 0 || hi >= len(bars) {
		return false, false
	}
	for k := lo; k <= hi; k++ {
		if !bars[k].Volume.GreaterThan(decimal.Zero) {
			return false, true
		}
	}
	return true, true
}

// ExplainDocument renders a plain-language explanation of a compiled document.
// explain 模式只产出说明文本，不修改草稿规则（§12.4.8）。
func ExplainDocument(doc Document) string {
	var b strings.Builder
	b.WriteString("策略说明：在 ")
	b.WriteString(doc.InstrumentID)
	b.WriteString(" 上按 ")
	b.WriteString(doc.SignalPeriod)
	b.WriteString(" 日线检查。买入条件：")
	b.WriteString(condSummary(doc.Entry))
	b.WriteString("。卖出条件：")
	b.WriteString(condSummary(doc.Exit))
	b.WriteString("。仓位：目标权益 ")
	b.WriteString(doc.Position.Value)
	b.WriteString("。风险：")
	if doc.Risk.StopLossPct != nil && *doc.Risk.StopLossPct != "" {
		b.WriteString("收盘检查止损 " + *doc.Risk.StopLossPct + "；")
	} else {
		b.WriteString("止损未启用；")
	}
	if doc.Risk.TakeProfitPct != nil && *doc.Risk.TakeProfitPct != "" {
		b.WriteString("止盈 " + *doc.Risk.TakeProfitPct + "；")
	}
	if doc.Risk.MaxHoldingBars != nil {
		b.WriteString(fmt.Sprintf("最多持有 %d 个信号日；", *doc.Risk.MaxHoldingBars))
	}
	b.WriteString("执行：下一交易日开盘模拟执行、退出优先。历史模拟不代表真实成交。")
	return b.String()
}

func condSummary(raw json.RawMessage) string {
	var obj map[string]json.RawMessage
	if json.Unmarshal(raw, &obj) != nil || obj == nil {
		return "（缺失）"
	}
	if kindRaw, ok := obj["kind"]; ok {
		kind := strings.Trim(string(kindRaw), `"`)
		if kind == "volume_increase" {
			days := 0
			_ = json.Unmarshal(obj["days"], &days)
			return fmt.Sprintf("最近连续 %d 个交易日成交量逐日增加", days)
		}
		return "快捷条件 " + kind
	}
	if list, ok := obj["all"]; ok {
		return groupSummary(list, " 且 ")
	}
	if list, ok := obj["any"]; ok {
		return groupSummary(list, " 或 ")
	}
	if not, ok := obj["not"]; ok {
		return "非（" + condSummary(not) + "）"
	}
	op := strings.Trim(string(obj["op"]), `"`)
	return operandSummary(obj["left"]) + " " + opLabel(op) + " " + operandSummary(obj["right"])
}

func groupSummary(list json.RawMessage, sep string) string {
	var items []json.RawMessage
	_ = json.Unmarshal(list, &items)
	parts := make([]string, 0, len(items))
	for _, it := range items {
		parts = append(parts, condSummary(it))
	}
	return "(" + strings.Join(parts, sep) + ")"
}

func operandSummary(raw json.RawMessage) string {
	var obj map[string]any
	if json.Unmarshal(raw, &obj) == nil && obj != nil {
		if c, ok := obj["constant"]; ok {
			s, _ := c.(string)
			return "常数 " + s
		}
		if ref, ok := obj["ref"].(string); ok {
			lag := 0
			if lr, ok := obj["lag"].(float64); ok {
				lag = int(lr)
			}
			if lag > 0 {
				return fmt.Sprintf("%s[滞后 %d 日]", ref, lag)
			}
			return ref
		}
		return "（未知操作数）"
	}
	var ref string
	if json.Unmarshal(raw, &ref) == nil {
		return ref
	}
	return "（缺失）"
}

func opLabel(op string) string {
	switch op {
	case "gt":
		return "高于"
	case "gte":
		return "不低于"
	case "lt":
		return "低于"
	case "lte":
		return "不高于"
	case "eq":
		return "等于"
	case "crosses_above":
		return "上穿"
	case "crosses_below":
		return "下穿"
	}
	return op
}

// ConvertToEditor explicitly converts a saved strategy.v1/v2 document into
// editor state. The server reports the conversion status instead of letting the
// client infer rules (§12.4.9); saving a converted draft creates a new version.
func ConvertToEditor(doc Document) (EditorState, string) {
	if doc.SchemaVersion != SchemaVersion && doc.SchemaVersion != SchemaVersionV2 {
		return EditorState{}, "not_convertible"
	}
	if err := convertibleCond(doc.Entry); err != nil {
		return EditorState{}, "not_convertible"
	}
	if err := convertibleCond(doc.Exit); err != nil {
		return EditorState{}, "not_convertible"
	}
	state := EditorState{
		Name: doc.Name, SignalPeriod: doc.SignalPeriod, PriceBasis: doc.PriceBasis,
		Indicators: doc.Indicators,
		Entry:      doc.Entry,
		Exit:       doc.Exit,
		Position:   doc.Position,
		Risk:       doc.Risk,
		Execution:  doc.Execution,
	}
	if doc.InstrumentID != "" {
		inst := doc.InstrumentID
		state.InstrumentID = &inst
	}
	return state, "convertible"
}

func convertibleCond(raw json.RawMessage) error {
	var obj map[string]json.RawMessage
	if json.Unmarshal(raw, &obj) != nil || obj == nil {
		return fmt.Errorf("条件缺失")
	}
	for k := range obj {
		switch k {
		case "all", "any", "not", "op", "left", "right", "lag":
		default:
			return fmt.Errorf("含不可转换字段 %s", k)
		}
	}
	for _, key := range []string{"all", "any"} {
		if list, ok := obj[key]; ok {
			var items []json.RawMessage
			_ = json.Unmarshal(list, &items)
			for _, it := range items {
				if err := convertibleCond(it); err != nil {
					return err
				}
			}
			return nil
		}
	}
	if not, ok := obj["not"]; ok {
		return convertibleCond(not)
	}
	if _, ok := obj["op"]; !ok {
		return fmt.Errorf("叶节点缺少 op")
	}
	return nil
}
